### ISSUE TITLE
Class<T>这种参数的类型要填什么呢？填java.lang.Class报错

### ISSUE THREAD

**Issue by githubnichen** [thubbo/jmeter-plugins-for-apache-dubbo#114]
<T> T getUser(long userId, Class<T> entityClass);
这是dubbo接口，jmeter中paramType填java.lang.Class，然后paramValue中填对应的实体类json数据，报错。报错信息：
java.lang.IllegalArgumentException: Invalid parameter => [ParamType=java.lang.Class,ParamValue={"userId":null,"kkkk":null,"depodddsit":null,"cuisine":null,"housework":null,"liveWithParentsInLaw":null,"liveWithParents":null,"parents":null,"fondDate":null,"marryDate":null,"pets":null,"personality":null,"workAttitude":null,"familySituation":null,"interests":null,"finishSchool":null,"lastModTime":null,"createTime":null}]
	at io.github.ningyu.jmeter.plugin.util.ClassUtils.parseParameter(ClassUtils.java:227) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample.callDubbo(DubboSample.java:291) [jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample.sample(DubboSample.java:67) [jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) [ApacheJMeter_core.jar:?]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) [ApacheJMeter_core.jar:?]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:?]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.UnsupportedOperationException: Attempted to deserialize a java.lang.Class. Forgot to register a type adapter?
	at com.google.gson.internal.bind.TypeAdapters$1.read(TypeAdapters.java:77) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$1.read(TypeAdapters.java:69) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:927) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:892) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:841) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:813) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at io.github.ningyu.jmeter.plugin.util.JsonUtils.formJson(JsonUtils.java:52) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	at io.github.ningyu.jmeter.plugin.util.ClassUtils.parseParameter(ClassUtils.java:209) ~[jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar:?]
	... 7 more

**Comment by ningyu1** [comment]
@githubnichen 
看这个https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/wiki/FAQ#%E5%A4%8D%E6%9D%82%E5%8F%82%E6%95%B0%E4%BD%BF%E7%94%A8%E6%A1%88%E4%BE%8B

**Comment by githubnichen** [comment]
这个我看过了，但是我的接口是这种<T> T getUser(long userId, Class<T> entityClass);
跟文档中的不一样。
 Class<T> entityClass这个参数的类型不知道要传什么？

**Comment by ningyu1** [comment]
第一个参数
type long
第二个参数
type {"属性":"值","class": "entityClass的完全类名（包含包名）"

**Comment by githubnichen** [comment]
试过了，不行呢。报找不到方法

**Comment by githubnichen** [comment]
这样传的话，会去找完全类名的方法，而找不到Class<T>类型的方法

**Comment by ningyu1** [comment]
找不到方法就两个问题，要么这个服务就没有注册到注册中心，要么就是通过参数类型和方法名称反射找不到方法（大多还是参数类型弄错了），去看api中的类方法描述

**Comment by ningyu1** [comment]
直接写java.lang.Class 肯定不行

**Comment by githubnichen** [comment]
是第二种情况，但是接口是要求传Class<T>类型的参数，如果传具体的类，会找不到方法

**Comment by githubnichen** [comment]
<T> T getUser(long userId, Class<T> entityClass);
接口就是这样

**Comment by ningyu1** [comment]
Class 这个对象确实现在处理不了

**Comment by githubnichen** [comment]
这个Class后面有一个泛型T，打不上去

**Comment by githubnichen** [comment]
其实我就想知道是dubbo的泛型调用处理不了，还是这个插件没有处理这种情况呢

**Comment by ningyu1** [comment]
插件没处理，目前插件支持的泛型是 xxx.XXXClass<T>  这种方式

**Comment by githubnichen** [comment]
如果要处理这种情况的话，有什么思路吗？我看您是直接调用的$invoke，然后有具体的对象，再将其转为map处理

**Comment by ningyu1** [comment]
这个用泛化不太能处理，Class太抽象，首先要知道那个具体的类型（xxxClass）然后再获取它的Class（大class描述类）
插件里面value的json要反序列化成目标对象（这里是具体的类对象不是描述类对象）所以作为通用的插件没发实现这个，除非你直接写javaclient sample定制写死。

**Comment by githubnichen** [comment]
正在直接写死。。。。。
