### ISSUE TITLE
Failed to invoke remote method: $invoke, provider:

### ISSUE THREAD

**Issue by tytyty123** [thubbo/jmeter-plugins-for-apache-dubbo#130]
想咨询下这种报错主要是哪种原因

2020-11-24 15:00:13,293 INFO c.a.d.c.AbstractConfig:  [DUBBO] Refer dubbo service com.alibaba.dubbo.rpc.service.GenericService from url zookeeper://192.168.1.4:2181/com.alibaba.dubbo.registry.RegistryService?alias=ǳҵ�ǎ򋓅���&anyhost=false&application=DubboSample&async=false&check=false&cluster=failfast&connections=100&dc=jd&dsf=1.3.9.2&dubbo=2.0.2&dubbo_route_master=1&dubbo_route_setnum=2&exposed=none&generic=true&interface=rpc.CommReimBatchSubmitATS__1_0&loadbalance=random&methods=commSubmit&organization=��??�ӿ܃&owner=F-TEST&pid=18908&protocol=dubbo&providerApp=TEST&region=sh&register.ip=192.168.1.6&remote.timestamp=1609463734926&retries=0&routeKey=groupId&router=rpc.framework.service.base.dubbo.router.HashRouter&side=consumer&tag=test&timeout=8000&timestamp=1606201206726, dubbo version: 1.3.8-jar-with-dependencies, current host: 192.168.1.6
2020-11-24 15:00:13,417 ERROR i.g.n.j.p.d.s.DubboSample: RpcException��
com.alibaba.dubbo.rpc.RpcException: Failfast invoke providers dubbo://192.168.1.5:35008/rpc.CommReimBatchSubmitATS__1_0?alias=ǳҵ�ǎ򋓅���&anyhost=false&application=DubboSample&async=false&check=false&cluster=failfast&connections=100&dc=jd&dsf=1.3.9.2&dubbo=2.0.2&dubbo_route_master=1&dubbo_route_setnum=4&exposed=none&generic=true&interface=rpc.CommReimBatchSubmitATS__1_0&loadbalance=random&methods=commSubmit&organization=��??�ӿ܃&owner=F-EBBC&pid=18908&protocol=dubbo&providerApp=TEST&region=sh&register.ip=192.168.1.6&remote.timestamp=1609461971159&retries=0&routeKey=groupId&router=rpc.framework.service.base.dubbo.router.HashRouter&side=consumer&tag=test_gray&timeout=8000&timestamp=1606201206726 RandomLoadBalance select from all providers [com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@230a6cab, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@394c5e48, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@682ac37a, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@19fd2111, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@69e279b1, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@3287d4db, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@c88e0e2, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@7c8dadcb, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@6d87c1a, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@a755116, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@41313f4a, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@50c32152, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@153ebffc, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@35e3b1ac, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@7de00335, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegate@3460746a] for service com.alibaba.dubbo.rpc.service.GenericService method $invoke on consumer 192.168.1.6 use dubbo version 1.3.8-jar-with-dependencies, but no luck to perform the invocation. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://192.168.1.5:35008/rpc.CommReimBatchSubmitATS__1_0?alias=ǳҵ�ǎ򋓅���&anyhost=false&application=DubboSample&async=false&check=false&cluster=failfast&connections=100&dc=jd&dsf=1.3.9.2&dubbo=2.0.2&dubbo_route_master=1&dubbo_route_setnum=4&exposed=none&generic=true&interface=rpc.CommReimBatchSubmitATS__1_0&loadbalance=random&methods=commSubmit&organization=��??�ӿ܃&owner=F-EBBC&pid=18908&protocol=dubbo&providerApp=TEST&region=sh&register.ip=192.168.1.6&remote.timestamp=1609461971159&retries=0&routeKey=groupId&router=rpc.framework.service.base.dubbo.router.HashRouter&side=consumer&tag=test_gray&timeout=8000&timestamp=1606201206726, cause: rpc.CommReimBatchSubmitATS.commSubmit(java.util.HashMap)
      at com.alibaba.dubbo.rpc.cluster.support.FailfastClusterInvoker.doInvoke(FailfastClusterInvoker.java:53) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:244) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.common.bytecode.proxy0.$invoke(proxy0.java) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample.callDubbo(DubboSample.java:548) [jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample.sample(DubboSample.java:346) [jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.0 r1840935]
      at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.0 r1840935]
      at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
      at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
      at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: com.alibaba.dubbo.remoting.RemotingException: rpc.CommReimBatchSubmitATS.commSubmit(java.util.HashMap)
      at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:245) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:162) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:135) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:154) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:77) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:172) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:49) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      at com.alibaba.dubbo.rpc.cluster.support.FailfastClusterInvoker.doInvoke(FailfastClusterInvoker.java:48) ~[jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar:?]
      ... 11 more

![1124_1](https://user-images.githubusercontent.com/30776468/100063820-b4d2ed80-2e6c-11eb-98c1-c75c4fceb296.jpg)

**Comment by ningyu1** [comment]
重点看这个
but no luck to perform the invocation. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://192.168.1.5:35008/rpc.CommReimBatchSubmitATS__1_0?

接口名字是这个rpc.CommReimBatchSubmitATS__1_0？

**Comment by tytyty123** [comment]
对，接口是这个名字

**Comment by ningyu1** [comment]
服务端使用的dubbo版本号是多少？
