### ISSUE TITLE
请求报错JMeter: Uncaught exception:  java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by yoobin0709** [thubbo/jmeter-plugins-for-apache-dubbo#90]
2.7.3-with-dependency版本，zookeeper方式，请求只有一个字符串类型参数：id。
参数取值为数据库中不存在的id时，可以请求成功，返回null；取值为1、123等测试人员用的简单id时也可以请求成功，返回用户信息；如果使用真实用户的id，如ff8012345678901234560879这类的，则会报错，实际上是有用户信息的。
报错日志如下：
2019-09-12 10:33:10,711 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-09-12 10:33:10,711 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-09-12 10:33:10,711 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2019-09-12 10:33:10,721 WARN o.a.d.c.AbstractConfig:  [DUBBO] ReferenceConfig(null) is not DESTROYED when FINALIZE, dubbo version: 2.7.3-jar-with-dependencies, current host: 192.168.56.1
2019-09-12 10:33:10,723 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2019-09-12 10:33:10,723 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2019-09-12 10:33:10,724 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-09-12 10:33:10,724 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2019-09-12 10:33:10,724 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-09-12 10:33:10,724 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2019-09-12 10:33:10,724 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2019-09-12 10:33:10,725 INFO i.g.n.j.p.d.s.DubboSample: sample中的实例idio.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample@183463ee,element名称FindUserById
2019-09-12 10:33:10,738 WARN o.a.d.c.AbstractConfig:  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3-jar-with-dependencies, current host: 192.168.56.1
2019-09-12 10:33:11,411 WARN o.a.d.c.AbstractConfig:  [DUBBO] ReferenceConfig(null) is not DESTROYED when FINALIZE, dubbo version: 2.7.3-jar-with-dependencies, current host: 192.168.56.1
2019-09-12 10:33:11,493 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2019-09-12 10:33:11,493 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.StackOverflowError: null
	at com.google.gson.stream.JsonWriter.newline(JsonWriter.java:601) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:618) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:307) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]	
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:205) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]

这中间几百条都是重复的com.google.gson.internal.bind这个包的三个报错日志

	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar:?]
2019-09-12 10:33:11,559 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2019-09-12 10:33:11,559 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by ningyu1** [comment]
@yoobin0709 能否提供一下你的接口描述和参数的具体类型与值？

**Comment by yoobin0709** [comment]
感谢大神回复，这个接口的功能是通过id获取实体，参数只有一个id，类型是String，值是uuid

**Comment by ningyu1** [comment]
无法复现，我先关闭这个问题
